/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiLayout2;

/**
 *
 * @author rkhis
 */
public class tagihan extends javax.swing.JFrame {
public static String paket;
public static int harga;

public static int pilih ;
public static int pilih1 = samsung.pilihan1;
public static int pilih2 = iphonex.pilihan3;

public static int pilih3 = cuci1.pilihan4;
public static int pilih4 = cuci2.pilihan5;
public static int pilih5 = cuci3.pilihan6;

public static int pilih6 = tv1.pilihan7;
public static int pilih7 = tv2.pilihan8;

public static int pilih8 = kulkas1.pilihan9;
public static int pilih9 = kulkas2.pilihan10;
public static int pilih10 = kulkas3.pilihan11;
    public tagihan() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("12 BULAN");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("3 BULAN");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 80, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("6 BULAN");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, -1));

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("JNE");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 100, -1));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("JNT");
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 100, -1));

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("KANTOR POSS");
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 100, -1));

        jButton1.setText("LANJUTKAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 130, 50));

        jLabel3.setFont(new java.awt.Font("Myriad Pro Light", 0, 24)); // NOI18N
        jLabel3.setText("PILIH JASA PENGIRIMAN :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 290, 40));

        jLabel2.setFont(new java.awt.Font("Myriad Pro Light", 0, 24)); // NOI18N
        jLabel2.setText("PILIH CICILAN PEMBAYARAN :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 134, 290, 40));

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 3, 80, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uiLayout2/polos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (jRadioButton2.isSelected()) {
            if (pilih == 1) {
            harga = 1300000/3;
        }else if (pilih1 == 2) {
            harga = 11499000/3;
        }else if (pilih2 == 3) {
            harga = 16750000/3;
        }else if (pilih3 == 4) {
            harga = 4500000/3;
        }else if (pilih4 == 5) {
            harga = 3500000/3;
        }else if (pilih5 == 6) {
            harga = 9800000/3;
        }else if (pilih6 == 7) {
            harga = 1700000/3;
        }else if (pilih7 == 8) {
            harga = 2600000/3;
        }else if (pilih8 == 9) {
            harga = 2100000/3;
        }else if (pilih9 == 10) {
            harga = 2100000/3;
        }else if (pilih10 == 11) {
            harga = 2900000/3;
        }
        }else if (jRadioButton3.isSelected()) {
            if (pilih == 1) {
            harga = 1300000/6;
        }else if (pilih1 == 2) {
            harga = 11499000/6;
        }else if (pilih2 == 3) {
            harga = 16750000/6;
        }else if (pilih3 == 4) {
            harga = 4500000/6;
        }else if (pilih4 == 5) {
            harga = 3500000/6;
        }else if (pilih5 == 6) {
            harga = 9800000/6;
        }else if (pilih6 == 7) {
            harga = 1700000/6;
        }else if (pilih7 == 8) {
            harga = 2600000/6;
        }else if (pilih8 == 9) {
            harga = 2100000/6;
        }else if (pilih9 == 10) {
            harga = 2100000/6;
        }else if (pilih10 == 11) {
            harga = 2900000/6;
        }
        }else if (jRadioButton1.isSelected()) {
            if (pilih == 1) {
            harga = 1300000/12;
        }else if (pilih1 == 2) {
            harga = 11499000/12;
        }else if (pilih2 == 3) {
            harga = 16750000/12;
        }else if (pilih3 == 4) {
            harga = 4500000/12;
        }else if (pilih4 == 5) {
            harga = 3500000/12;
        }else if (pilih5 == 6) {
            harga = 9800000/12;
        }else if (pilih6 == 7) {
            harga = 1700000/12;
        }else if (pilih7 == 8) {
            harga = 2600000/12;
        }else if (pilih8 == 9) {
            harga = 2100000/12;
        }else if (pilih9 == 10) {
            harga = 2100000/12;
        }else if (pilih10 == 11) {
            harga = 2900000/12;
        }
        }
    
    if (jRadioButton1.isSelected()) {
            paket = "JNE -Rp.30.000";
        }else if (jRadioButton2.isSelected()) {
            paket = "JNT -Rp.35.000";
        }else if (jRadioButton3.isSelected()) {
            paket = "KANTOR POSS -Rp.40.000";
        }
    new pembayaran().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    new uiMenu().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tagihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tagihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    // End of variables declaration//GEN-END:variables
}
